/** @file HelpDialog.java
 * @brief  帮助界面
 * @author 侯奇
 * @author 卢嘉勋
 * @author 刘菁菁
 * @date 2013-12-30
 * @version 1.0.0
 * 
 */
package connect6ng;

/**
 * @brief 帮助类
 * @author houqi1993
 * 
 */
@SuppressWarnings("serial")
public class HelpDialog extends javax.swing.JDialog {
	
	/**
	 * @brief Creates new form HelpDialog
	 * @param parent
	 * @param modal
	 */
	public HelpDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * @brief This method is called from within the constructor to initialize the form.
	 *  WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		contentArea = new javax.swing.JTextArea();
		icon_label = new javax.swing.JLabel();
		title_label = new javax.swing.JLabel();
		OK_btn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		contentArea.setColumns(20);
		contentArea.setFont(new java.awt.Font("华文楷体", 0, 14)); // NOI18N
		contentArea.setLineWrap(true);
		contentArea.setRows(5);
		contentArea
				.setText("简介：\n经过证明，传统的五子棋、连珠棋由于棋规的限制" +
						"，会出现“先手必胜”、“必胜下法”等有碍公平性的现象。" +
						"为了解决这些问题，六子棋应运而生。六子棋英文名称为conne" +
						"ct6，兼顾公平性和可玩性，是一种新的棋盘玩法，发明人为" +
						"国立交通大学资讯工程系教授吴毅成。\n\n规则：\n六子棋的" +
						"规则与五子棋非常相似，均有对弈双方轮流落子，先连成6子" +
						"者获胜。对弈过程中，除了第一次黑方只允许下一颗子外，之" +
						"后黑白双方每次落子均为两子，在此过程中双方可以对对方进" +
						"行围堵，同时也可以“明修栈道，暗度陈仓”，对弈双方在方" +
						"寸间斗智斗勇，最终决出胜利者。");
		jScrollPane1.setViewportView(contentArea);

		icon_label.setIcon(new javax.swing.ImageIcon(
				"./res/logo_100.png")); // NOI18N

		title_label.setFont(new java.awt.Font("华文行楷", 1, 22)); // NOI18N
		title_label.setText("六子棋小游戏");

		OK_btn.setText("确定");
		OK_btn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OK_btnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(0, 58, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		icon_label)
																.addGap(26, 26,
																		26)
																.addComponent(
																		title_label)
																.addContainerGap(
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		330,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(50, 50,
																		50))))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(168, 168, 168)
								.addComponent(OK_btn,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										98,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		icon_label)
																.addGap(18, 18,
																		18))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		title_label)
																.addGap(50, 50,
																		50)))
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										154,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(OK_btn)
								.addGap(23, 23, 23)));
		
		setTitle("六子棋帮助");
		pack();
	}// </editor-fold>
	
	/**
	 * @brief 确定按钮回调函数
	 * @param evt
	 */
	private void OK_btnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		HelpDialog.this.dispose();
	}

	// Variables declaration - do not modify
	private javax.swing.JButton OK_btn;
	private javax.swing.JTextArea contentArea;
	private javax.swing.JLabel icon_label;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel title_label;
	// End of variables declaration
}
