package connect6ng;

/**
 *
 * @author houqi1993
 */
@SuppressWarnings("serial")
public class AboutDialog extends javax.swing.JDialog {

    /**
     * Creates new form AboutDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        OK_btn = new javax.swing.JButton();
        title_label = new javax.swing.JLabel();
        author_label = new javax.swing.JLabel();
        version_label = new javax.swing.JLabel();
        copyright_label = new javax.swing.JLabel();
        icon_label = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        OK_btn.setText("确定");
        OK_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_btnActionPerformed(evt);
            }
        });

        title_label.setFont(new java.awt.Font("华文行楷", 1, 22)); // NOI18N
        title_label.setText("六子棋小游戏");

        author_label.setFont(new java.awt.Font("华文楷体", 1, 14)); // NOI18N
        author_label.setText("软件工程六子棋项目组");

        version_label.setFont(new java.awt.Font("华文楷体", 1, 14)); // NOI18N
        version_label.setText("版本：1.0.0 ");

        copyright_label.setFont(new java.awt.Font("华文楷体", 1, 14)); // NOI18N
        copyright_label.setText("版权所有归 软件工程六子棋项目组 所有 ");

        icon_label.setIcon(new javax.swing.ImageIcon("./res/logo_100.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_label)
                .addGap(24, 24, 24)
                .addComponent(title_label)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(author_label)
                            .addComponent(version_label)
                            .addComponent(copyright_label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(OK_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {author_label, copyright_label, version_label});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(title_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(icon_label)))
                .addGap(32, 32, 32)
                .addComponent(author_label)
                .addGap(10, 10, 10)
                .addComponent(version_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyright_label)
                .addGap(18, 18, 18)
                .addComponent(OK_btn)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {author_label, copyright_label, version_label});

        pack();
        
        setResizable(false);
    }// </editor-fold>//GEN-END:initComponents

    private void OK_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_btnActionPerformed
        // TODO add your handling code here:
        AboutDialog.this.dispose();
    }//GEN-LAST:event_OK_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK_btn;
    private javax.swing.JLabel author_label;
    private javax.swing.JLabel copyright_label;
    private javax.swing.JLabel icon_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel title_label;
    private javax.swing.JLabel version_label;
    // End of variables declaration//GEN-END:variables
}
